"""Add SavedContact model

Revision ID: 010289d05c0d
Revises: 960067b15322
Create Date: 2025-06-19 09:16:36.153760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010289d05c0d'
down_revision = '960067b15322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_contact')
    # ### end Alembic commands ###
