"""Added beneficiary_name to Transaction

Revision ID: 17a87b483473
Revises: 010289d05c0d
Create Date: 2025-06-19 12:00:13.399559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a87b483473'
down_revision = '010289d05c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('beneficiary_name')

    # ### end Alembic commands ###
