"""Add smart_saver fields to FinancialGoal

Revision ID: 2f30f2f27f80
Revises: 6aaafbfd88c9
Create Date: 2025-06-23 14:50:09.518852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f30f2f27f80'
down_revision = '6aaafbfd88c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_saved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('smart_saver_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_column('smart_saver_balance')
        batch_op.drop_column('last_saved_at')

    # ### end Alembic commands ###
