"""Add name to FinancialGoal

Revision ID: c6ef8b1ef76f
Revises: 2f30f2f27f80
Create Date: 2025-06-24 12:15:10.190633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ef8b1ef76f'
down_revision = '2f30f2f27f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goal', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
